name = "LVLcraft"
author = "lunarydess"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2365afe6d973c43f0e3d2846ba8f9ad47081ca7cde793cf543ba51875acbcf35"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
