name = "LVLcraft"
author = "lunarydess"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8233294e278626c983d4b51781c52ceada3f0d24764af829c7dff17a2e82cd06"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
