name = "LVLcraft"
author = "lunarydess"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6460669b91d584e96e1bcdaf442cccc266b07f556ad60d29495e9f34a8350105"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
